// src/constants/itemBases.ts

import { ItemBase } from '../types/items';

export const ITEM_BASES: { [id: string]: ItemBase } = {
  // --- 1. POLERARM / HALBERD (Strength / Dex / Wisdom scaling) ---
  halberd_dread: {
    id: 'halberd_dread',
    name: 'Astral Halberd',
    category: 'weapon_polearm',
    slot: 'mainHand',
    scalingClass: 'hybrid',
    baseScalings: [
      { stat: 'strength', grade: 'B', percentPerPoint: 0.024 },
      { stat: 'dexterity', grade: 'B', percentPerPoint: 0.022 },
      { stat: 'wisdom', grade: 'C', percentPerPoint: 0.018 },
    ],
    equipLoad: 12,
    width: 2,
    height: 3,
    reqLevel: 1,
    reqStr: 10,
    reqDex: 10,
    reqInt: 0,
    icon: 'Sword',
    color: '#38bdf8',
    implicit: {
      text: '+15% Melee Reach & Sweeping Cleave',
      statKey: 'increasedAreaDamage',
      minValue: 10,
      maxValue: 18,
    },
    baseStats: {
      physicalDamageMin: 18,
      physicalDamageMax: 34,
      attackSpeed: 1.25,
      critChance: 6.0,
    },
  },

  // --- 2. QUARTERSTAFF (Wisdom / Dex scaling) ---
  quarterstaff_willow: {
    id: 'quarterstaff_willow',
    name: 'Monk Quarterstaff',
    category: 'weapon_quarterstaff',
    slot: 'mainHand',
    scalingClass: 'hybrid',
    baseScalings: [
      { stat: 'wisdom', grade: 'A', percentPerPoint: 0.032 },
      { stat: 'dexterity', grade: 'B', percentPerPoint: 0.026 },
    ],
    equipLoad: 7,
    width: 1,
    height: 3,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 10,
    reqInt: 0,
    icon: 'Wand',
    color: '#a855f7',
    implicit: {
      text: '+8% Chance to Block Attacks & +10% Cast Speed',
      statKey: 'blockChance',
      minValue: 6,
      maxValue: 10,
    },
    baseStats: {
      physicalDamageMin: 14,
      physicalDamageMax: 26,
      attackSpeed: 1.45,
      critChance: 6.5,
    },
  },

  // --- 3. FIST WEAPONS (Caestus / Katar) (Dex / Willpower scaling) ---
  bladed_katar: {
    id: 'bladed_katar',
    name: 'Bladed Katar Caestus',
    category: 'weapon_fist',
    slot: 'mainHand',
    scalingClass: 'light',
    baseScalings: [
      { stat: 'dexterity', grade: 'A', percentPerPoint: 0.034 },
      { stat: 'willpower', grade: 'B', percentPerPoint: 0.025 },
    ],
    equipLoad: 3,
    width: 1,
    height: 2,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 12,
    reqInt: 0,
    icon: 'Hand',
    color: '#22c55e',
    implicit: {
      text: '+35% Global Critical Multiplier on Rapid Hits',
      statKey: 'critMultiplier',
      minValue: 25,
      maxValue: 35,
    },
    baseStats: {
      physicalDamageMin: 10,
      physicalDamageMax: 20,
      attackSpeed: 1.65,
      critChance: 8.0,
    },
  },

  // --- 4. CURVED GREATSWORD (Strength / Luck / light Dex scaling) ---
  murakumo_greatsword: {
    id: 'murakumo_greatsword',
    name: 'Murakumo Curved Greatsword',
    category: 'weapon_curved_greatsword',
    slot: 'mainHand',
    scalingClass: 'heavy',
    baseScalings: [
      { stat: 'strength', grade: 'A', percentPerPoint: 0.032 },
      { stat: 'luck', grade: 'B', percentPerPoint: 0.026 },
      { stat: 'dexterity', grade: 'D', percentPerPoint: 0.012 },
    ],
    equipLoad: 16,
    width: 2,
    height: 3,
    reqLevel: 1,
    reqStr: 14,
    reqDex: 8,
    reqInt: 0,
    icon: 'Sword',
    color: '#f59e0b',
    implicit: {
      text: '+20% Damage Roll Ceiling from Luck',
      statKey: 'critChance',
      minValue: 5,
      maxValue: 10,
    },
    baseStats: {
      physicalDamageMin: 22,
      physicalDamageMax: 46,
      attackSpeed: 1.15,
      critChance: 6.5,
    },
  },

  // --- 5. POLEAXE (Strength / Willpower scaling) ---
  vanguard_poleaxe: {
    id: 'vanguard_poleaxe',
    name: 'Vanguard Poleaxe',
    category: 'weapon_poleaxe',
    slot: 'mainHand',
    scalingClass: 'heavy',
    baseScalings: [
      { stat: 'strength', grade: 'S', percentPerPoint: 0.038 },
      { stat: 'willpower', grade: 'B', percentPerPoint: 0.024 },
    ],
    equipLoad: 14,
    width: 2,
    height: 3,
    reqLevel: 1,
    reqStr: 14,
    reqDex: 0,
    reqInt: 0,
    icon: 'Axe',
    color: '#ef4444',
    implicit: {
      text: '+25% Armor Penetration on Heavy Attacks',
      statKey: 'increasedPhysicalDamage',
      minValue: 10,
      maxValue: 20,
    },
    baseStats: {
      physicalDamageMin: 24,
      physicalDamageMax: 44,
      attackSpeed: 1.1,
      critChance: 5.0,
    },
  },

  // --- 6. POLEBLADE (Dexterity / Willpower scaling) ---
  astral_poleblade: {
    id: 'astral_poleblade',
    name: 'Astral Poleblade',
    category: 'weapon_poleblade',
    slot: 'mainHand',
    scalingClass: 'light',
    baseScalings: [
      { stat: 'dexterity', grade: 'S', percentPerPoint: 0.036 },
      { stat: 'willpower', grade: 'B', percentPerPoint: 0.026 },
    ],
    equipLoad: 8,
    width: 2,
    height: 3,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 14,
    reqInt: 0,
    icon: 'Sword',
    color: '#06b6d4',
    implicit: {
      text: '+15% increased Attack & Movement Speed',
      statKey: 'movementSpeed',
      minValue: 10,
      maxValue: 15,
    },
    baseStats: {
      physicalDamageMin: 16,
      physicalDamageMax: 30,
      attackSpeed: 1.5,
      critChance: 7.0,
    },
  },

  // --- 7. FLAIL (Pure Luck scaling) ---
  fortune_flail: {
    id: 'fortune_flail',
    name: "Fortune's Heavy Flail",
    category: 'weapon_flail',
    slot: 'mainHand',
    scalingClass: 'hybrid',
    baseScalings: [
      { stat: 'luck', grade: 'S', percentPerPoint: 0.048 }, // Pure massive luck scaling!
    ],
    equipLoad: 8,
    width: 1,
    height: 3,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 0,
    reqInt: 0,
    icon: 'Hammer',
    color: '#eab308',
    implicit: {
      text: '+30% Global Critical Strike Chance & High Rolls',
      statKey: 'critChance',
      minValue: 25,
      maxValue: 35,
    },
    baseStats: {
      physicalDamageMin: 8,
      physicalDamageMax: 48, // Wide spread perfectly maximized by Luck!
      attackSpeed: 1.3,
      critChance: 7.5,
    },
  },

  // --- 8. WARHAMMER (Strength / Wisdom scaling) ---
  titan_warhammer: {
    id: 'titan_warhammer',
    name: 'Sanctified Warhammer',
    category: 'weapon_warhammer',
    slot: 'mainHand',
    scalingClass: 'heavy',
    baseScalings: [
      { stat: 'strength', grade: 'A', percentPerPoint: 0.034 },
      { stat: 'wisdom', grade: 'B', percentPerPoint: 0.026 },
    ],
    equipLoad: 15,
    width: 2,
    height: 3,
    reqLevel: 1,
    reqStr: 14,
    reqDex: 0,
    reqInt: 0,
    icon: 'Hammer',
    color: '#f59e0b',
    implicit: {
      text: '+20% Area of Effect on Heavy Slams',
      statKey: 'areaOfEffectMultiplier',
      minValue: 15,
      maxValue: 25,
    },
    baseStats: {
      physicalDamageMin: 26,
      physicalDamageMax: 50,
      attackSpeed: 1.05,
      critChance: 5.5,
    },
  },

  // --- 9. WAND (Pure Wisdom scaling) ---
  driftwood_wand: {
    id: 'driftwood_wand',
    name: 'Arcane Wand',
    category: 'weapon_wand',
    slot: 'mainHand',
    scalingClass: 'magical',
    baseScalings: [
      { stat: 'wisdom', grade: 'S', percentPerPoint: 0.045 },
    ],
    equipLoad: 3,
    width: 1,
    height: 3,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 0,
    reqInt: 10,
    icon: 'Wand2',
    color: '#3b82f6',
    implicit: {
      text: '+20% increased Spell & Magical Damage',
      statKey: 'increasedSpellDamage',
      minValue: 15,
      maxValue: 25,
    },
    baseStats: {
      physicalDamageMin: 8,
      physicalDamageMax: 16,
      attackSpeed: 1.25,
      critChance: 7.0,
    },
  },

  // --- 10. STAFF (Wisdom / Willpower / light Strength scaling) ---
  celestial_staff: {
    id: 'celestial_staff',
    name: 'Celestial Archon Staff',
    category: 'weapon_staff',
    slot: 'mainHand',
    scalingClass: 'magical',
    baseScalings: [
      { stat: 'wisdom', grade: 'A', percentPerPoint: 0.032 },
      { stat: 'willpower', grade: 'B', percentPerPoint: 0.024 },
      { stat: 'strength', grade: 'D', percentPerPoint: 0.012 },
    ],
    equipLoad: 9,
    width: 1,
    height: 3,
    reqLevel: 1,
    reqStr: 8,
    reqDex: 0,
    reqInt: 10,
    icon: 'Wand2',
    color: '#8b5cf6',
    implicit: {
      text: '+25% Status Effect Duration & Magnitude',
      statKey: 'increasedSpellDamage',
      minValue: 15,
      maxValue: 25,
    },
    baseStats: {
      physicalDamageMin: 16,
      physicalDamageMax: 32,
      attackSpeed: 1.2,
      critChance: 6.5,
    },
  },

  // --- 11. TWIN SICKLES / SCYTHE (Dex / Wisdom / Luck scaling) ---
  reaper_scythe: {
    id: 'reaper_scythe',
    name: 'Reaper Twin Sickles',
    category: 'weapon_scythe',
    slot: 'mainHand',
    scalingClass: 'hybrid',
    baseScalings: [
      { stat: 'dexterity', grade: 'B', percentPerPoint: 0.026 },
      { stat: 'wisdom', grade: 'B', percentPerPoint: 0.022 },
      { stat: 'luck', grade: 'C', percentPerPoint: 0.018 },
    ],
    equipLoad: 6,
    width: 2,
    height: 3,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 12,
    reqInt: 0,
    icon: 'Scissors',
    color: '#a855f7',
    implicit: {
      text: '+20% Chance to Inflict Severe Bleed & Poison',
      statKey: 'chanceToBleed',
      minValue: 15,
      maxValue: 25,
    },
    baseStats: {
      physicalDamageMin: 14,
      physicalDamageMax: 28,
      attackSpeed: 1.45,
      critChance: 7.5,
    },
  },

  // --- 12. GREATBOW (Strength / Dexterity scaling) ---
  titan_greatbow: {
    id: 'titan_greatbow',
    name: 'Ballista Greatbow',
    category: 'weapon_greatbow',
    slot: 'mainHand',
    scalingClass: 'heavy',
    baseScalings: [
      { stat: 'strength', grade: 'A', percentPerPoint: 0.032 },
      { stat: 'dexterity', grade: 'A', percentPerPoint: 0.030 },
    ],
    equipLoad: 11,
    width: 2,
    height: 3,
    reqLevel: 1,
    reqStr: 12,
    reqDex: 12,
    reqInt: 0,
    icon: 'Target',
    color: '#ea580c',
    implicit: {
      text: '+2 Pierce & Heavy Impact Knockback',
      statKey: 'pierceCount',
      minValue: 2,
      maxValue: 3,
    },
    baseStats: {
      physicalDamageMin: 25,
      physicalDamageMax: 48,
      attackSpeed: 1.15,
      critChance: 6.5,
    },
  },

  // --- 13. SPELLBLADE (Dexterity / Wisdom scaling) ---
  rune_spellblade: {
    id: 'rune_spellblade',
    name: 'Runic Spellblade',
    category: 'weapon_spellblade',
    slot: 'mainHand',
    scalingClass: 'hybrid',
    baseScalings: [
      { stat: 'dexterity', grade: 'A', percentPerPoint: 0.032 },
      { stat: 'wisdom', grade: 'A', percentPerPoint: 0.032 },
    ],
    equipLoad: 4,
    width: 1,
    height: 3,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 10,
    reqInt: 10,
    icon: 'Sword',
    color: '#06b6d4',
    implicit: {
      text: '+20% of Physical Damage Converted to Elemental',
      statKey: 'increasedElementalDamage',
      minValue: 15,
      maxValue: 25,
    },
    baseStats: {
      physicalDamageMin: 12,
      physicalDamageMax: 24,
      attackSpeed: 1.5,
      critChance: 7.0,
    },
  },

  // --- 14. ASTRAL FOCUS (Wisdom / Willpower / Luck scaling) ---
  astral_focus: {
    id: 'astral_focus',
    name: 'Astral Relic Catalyst',
    category: 'weapon_relic_focus',
    slot: 'mainHand',
    scalingClass: 'magical',
    baseScalings: [
      { stat: 'wisdom', grade: 'A', percentPerPoint: 0.030 },
      { stat: 'willpower', grade: 'A', percentPerPoint: 0.030 },
      { stat: 'luck', grade: 'C', percentPerPoint: 0.016 },
    ],
    equipLoad: 3,
    width: 1,
    height: 2,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 0,
    reqInt: 12,
    icon: 'Gem',
    color: '#c084fc',
    implicit: {
      text: '+30% Minion & Spectral Damage',
      statKey: 'increasedMinionDamage',
      minValue: 20,
      maxValue: 35,
    },
    baseStats: {
      physicalDamageMin: 10,
      physicalDamageMax: 20,
      attackSpeed: 1.35,
      critChance: 8.0,
    },
  },

  // --- 15. CLASSICAL GREATSWORD ---
  rusty_greatsword: {
    id: 'rusty_greatsword',
    name: 'Bastion Greatsword',
    category: 'weapon_melee_2h',
    slot: 'mainHand',
    scalingClass: 'heavy',
    baseScalings: [
      { stat: 'strength', grade: 'S', percentPerPoint: 0.036 },
      { stat: 'dexterity', grade: 'C', percentPerPoint: 0.016 },
    ],
    equipLoad: 14,
    width: 2,
    height: 3,
    reqLevel: 1,
    reqStr: 12,
    reqDex: 0,
    reqInt: 0,
    icon: 'Sword',
    color: '#ef4444',
    implicit: {
      text: '+20% increased Stun Duration on Enemies',
      statKey: 'increasedPhysicalDamage',
      minValue: 5,
      maxValue: 10,
    },
    baseStats: {
      physicalDamageMin: 18,
      physicalDamageMax: 34,
      attackSpeed: 1.15,
      critChance: 5.0,
    },
  },

  // --- 16. CLASSICAL RECURVE BOW ---
  crude_bow: {
    id: 'crude_bow',
    name: 'Recurve Bow',
    category: 'weapon_bow',
    slot: 'mainHand',
    scalingClass: 'light',
    baseScalings: [
      { stat: 'dexterity', grade: 'S', percentPerPoint: 0.038 },
      { stat: 'luck', grade: 'C', percentPerPoint: 0.016 },
    ],
    equipLoad: 5,
    width: 2,
    height: 3,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 12,
    reqInt: 0,
    icon: 'Target',
    color: '#22c55e',
    implicit: {
      text: '+15% increased Projectile Speed',
      statKey: 'projectileSpeedMultiplier',
      minValue: 10,
      maxValue: 15,
    },
    baseStats: {
      physicalDamageMin: 10,
      physicalDamageMax: 22,
      attackSpeed: 1.4,
      critChance: 6.0,
    },
  },

  // --- 17. CLASSICAL ASSASSIN SHANK ---
  glass_shank: {
    id: 'glass_shank',
    name: 'Assassins Shank',
    category: 'weapon_dagger',
    slot: 'mainHand',
    scalingClass: 'light',
    baseScalings: [
      { stat: 'dexterity', grade: 'A', percentPerPoint: 0.032 },
      { stat: 'luck', grade: 'A', percentPerPoint: 0.032 },
    ],
    equipLoad: 2,
    width: 1,
    height: 2,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 10,
    reqInt: 0,
    icon: 'Knife',
    color: '#a855f7',
    implicit: {
      text: '+30% to Global Critical Strike Chance',
      statKey: 'critChance',
      minValue: 25,
      maxValue: 35,
    },
    baseStats: {
      physicalDamageMin: 9,
      physicalDamageMax: 18,
      attackSpeed: 1.55,
      critChance: 8.0,
    },
  },

  // --- OFFHAND & SHIELDS ---
  tower_shield: {
    id: 'tower_shield',
    name: 'Spiked Tower Aegis',
    category: 'armour_shield',
    slot: 'offHand',
    equipLoad: 12,
    width: 2,
    height: 2,
    reqLevel: 3,
    reqStr: 14,
    reqDex: 0,
    reqInt: 0,
    icon: 'Shield',
    color: '#ef4444',
    implicit: {
      text: '+25 to Maximum Life & +15% Block',
      statKey: 'maxLife',
      minValue: 20,
      maxValue: 30,
    },
    baseStats: {
      armor: 75,
      blockChance: 25,
    },
  },
  spirit_shield: {
    id: 'spirit_shield',
    name: 'Aetheric Ward Shield',
    category: 'armour_shield',
    slot: 'offHand',
    equipLoad: 4,
    width: 2,
    height: 2,
    reqLevel: 3,
    reqStr: 0,
    reqDex: 0,
    reqInt: 12,
    icon: 'Shield',
    color: '#3b82f6',
    implicit: {
      text: '+15% increased Spell Damage & Energy Shield',
      statKey: 'increasedSpellDamage',
      minValue: 10,
      maxValue: 18,
    },
    baseStats: {
      energyShield: 45,
      blockChance: 18,
    },
  },
  serrated_quiver: {
    id: 'serrated_quiver',
    name: 'Serrated Arrow Quiver',
    category: 'armour_quiver',
    slot: 'offHand',
    equipLoad: 3,
    width: 2,
    height: 2,
    reqLevel: 2,
    reqStr: 0,
    reqDex: 12,
    reqInt: 0,
    icon: 'Target',
    color: '#22c55e',
    implicit: {
      text: 'Adds 3 to 8 Physical Damage to Bow Attacks',
      statKey: 'addedPhysicalDamageMax',
      minValue: 5,
      maxValue: 8,
    },
    baseStats: {},
  },

  // --- ARMORS ---
  plate_vest: {
    id: 'plate_vest',
    name: 'Reinforced Plate',
    category: 'armour_body',
    slot: 'bodyArmor',
    equipLoad: 16,
    width: 2,
    height: 3,
    reqLevel: 1,
    reqStr: 12,
    reqDex: 0,
    reqInt: 0,
    icon: 'Shirt',
    color: '#ef4444',
    baseStats: {
      armor: 65,
    },
  },
  leather_tunic: {
    id: 'leather_tunic',
    name: 'Scouts Leather',
    category: 'armour_body',
    slot: 'bodyArmor',
    equipLoad: 8,
    width: 2,
    height: 3,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 12,
    reqInt: 0,
    icon: 'Shirt',
    color: '#22c55e',
    baseStats: {
      evasion: 70,
    },
  },
  silk_robe: {
    id: 'silk_robe',
    name: 'Aetheric Silk Robe',
    category: 'armour_body',
    slot: 'bodyArmor',
    equipLoad: 4,
    width: 2,
    height: 3,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 0,
    reqInt: 12,
    icon: 'Shirt',
    color: '#3b82f6',
    baseStats: {
      energyShield: 45,
    },
  },
  astral_plate: {
    id: 'astral_plate',
    name: 'Astral Plate',
    category: 'armour_body',
    slot: 'bodyArmor',
    equipLoad: 24,
    width: 2,
    height: 3,
    reqLevel: 20,
    reqStr: 45,
    reqDex: 0,
    reqInt: 0,
    icon: 'Shirt',
    color: '#ef4444',
    implicit: {
      text: '+12% to all Elemental Resistances',
      statKey: 'fireResistance',
      minValue: 10,
      maxValue: 14,
    },
    baseStats: {
      armor: 220,
    },
  },

  // --- HELMETS, GLOVES, BOOTS ---
  iron_sallet: {
    id: 'iron_sallet',
    name: 'Iron Sallet',
    category: 'armour_helmet',
    slot: 'helmet',
    equipLoad: 6,
    width: 2,
    height: 2,
    reqLevel: 1,
    reqStr: 10,
    reqDex: 0,
    reqInt: 0,
    icon: 'Crown',
    baseStats: {
      armor: 30,
    },
  },
  hunter_hood: {
    id: 'hunter_hood',
    name: 'Hunter Hood',
    category: 'armour_helmet',
    slot: 'helmet',
    equipLoad: 3,
    width: 2,
    height: 2,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 10,
    reqInt: 0,
    icon: 'Crown',
    baseStats: {
      evasion: 35,
    },
  },
  riveted_gauntlets: {
    id: 'riveted_gauntlets',
    name: 'Riveted Gauntlets',
    category: 'armour_gloves',
    slot: 'gloves',
    equipLoad: 4,
    width: 2,
    height: 2,
    reqLevel: 1,
    reqStr: 8,
    reqDex: 0,
    reqInt: 0,
    icon: 'Hand',
    baseStats: {
      armor: 22,
    },
  },
  iron_greaves: {
    id: 'iron_greaves',
    name: 'Iron Greaves',
    category: 'armour_boots',
    slot: 'boots',
    equipLoad: 6,
    width: 2,
    height: 2,
    reqLevel: 1,
    reqStr: 8,
    reqDex: 0,
    reqInt: 0,
    icon: 'Footprints',
    baseStats: {
      armor: 22,
    },
  },

  // --- ACCESSORIES ---
  ruby_ring: {
    id: 'ruby_ring',
    name: 'Ruby Ring',
    category: 'accessory_ring',
    slot: 'ring',
    equipLoad: 0,
    width: 1,
    height: 1,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 0,
    reqInt: 0,
    icon: 'CircleDot',
    implicit: {
      text: '+25% to Fire Resistance',
      statKey: 'fireResistance',
      minValue: 20,
      maxValue: 30,
    },
    baseStats: {},
  },
  sapphire_ring: {
    id: 'sapphire_ring',
    name: 'Sapphire Ring',
    category: 'accessory_ring',
    slot: 'ring',
    equipLoad: 0,
    width: 1,
    height: 1,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 0,
    reqInt: 0,
    icon: 'CircleDot',
    implicit: {
      text: '+25% to Cold Resistance',
      statKey: 'coldResistance',
      minValue: 20,
      maxValue: 30,
    },
    baseStats: {},
  },
  topaz_ring: {
    id: 'topaz_ring',
    name: 'Topaz Ring',
    category: 'accessory_ring',
    slot: 'ring',
    equipLoad: 0,
    width: 1,
    height: 1,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 0,
    reqInt: 0,
    icon: 'CircleDot',
    implicit: {
      text: '+25% to Lightning Resistance',
      statKey: 'lightningResistance',
      minValue: 20,
      maxValue: 30,
    },
    baseStats: {},
  },
  amber_amulet: {
    id: 'amber_amulet',
    name: 'Amber Amulet',
    category: 'accessory_amulet',
    slot: 'amulet',
    equipLoad: 0,
    width: 1,
    height: 1,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 0,
    reqInt: 0,
    icon: 'Gem',
    implicit: {
      text: '+15 to Strength & Vigor',
      statKey: 'strength',
      minValue: 12,
      maxValue: 18,
    },
    baseStats: {},
  },
  leather_belt: {
    id: 'leather_belt',
    name: 'Leather Belt',
    category: 'accessory_belt',
    slot: 'belt',
    equipLoad: 1,
    width: 2,
    height: 1,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 0,
    reqInt: 0,
    icon: 'Link',
    implicit: {
      text: '+35 to Maximum Life',
      statKey: 'maxLife',
      minValue: 25,
      maxValue: 40,
    },
    baseStats: {},
  },

  // --- FLASKS ---
  small_life_flask: {
    id: 'small_life_flask',
    name: 'Vitality Elixir',
    category: 'flask',
    slot: 'flask',
    equipLoad: 1,
    width: 1,
    height: 2,
    reqLevel: 1,
    reqStr: 0,
    reqDex: 0,
    reqInt: 0,
    icon: 'FlaskConical',
    color: '#ef4444',
    baseStats: {},
    flavor: 'Recovers 120 Life over 4.0 seconds.',
  },
  large_life_flask: {
    id: 'large_life_flask',
    name: 'Grand Vitality Elixir',
    category: 'flask',
    slot: 'flask',
    equipLoad: 1,
    width: 1,
    height: 2,
    reqLevel: 12,
    reqStr: 0,
    reqDex: 0,
    reqInt: 0,
    icon: 'FlaskConical',
    color: '#ef4444',
    baseStats: {},
    flavor: 'Recovers 450 Life over 3.5 seconds.',
  },
  quicksilver_flask: {
    id: 'quicksilver_flask',
    name: 'Fleetfoot Draught',
    category: 'flask',
    slot: 'flask',
    equipLoad: 1,
    width: 1,
    height: 2,
    reqLevel: 4,
    reqStr: 0,
    reqDex: 0,
    reqInt: 0,
    icon: 'FlaskConical',
    color: '#22c55e',
    baseStats: {},
    flavor: '+40% increased Movement Speed for 4.0 seconds.',
  },

  // --- MAPS ---
  waystone_t1: {
    id: 'waystone_t1',
    name: 'Astral Rift: Catacomb of Echoes',
    category: 'map',
    slot: 'none',
    equipLoad: 0,
    width: 1,
    height: 1,
    reqLevel: 25,
    reqStr: 0,
    reqDex: 0,
    reqInt: 0,
    icon: 'Compass',
    color: '#eab308',
    baseStats: {},
  },
  waystone_t5: {
    id: 'waystone_t5',
    name: 'Astral Rift: Solar Spires',
    category: 'map',
    slot: 'none',
    equipLoad: 0,
    width: 1,
    height: 1,
    reqLevel: 40,
    reqStr: 0,
    reqDex: 0,
    reqInt: 0,
    icon: 'Compass',
    color: '#f97316',
    baseStats: {},
  },
  waystone_t10: {
    id: 'waystone_t10',
    name: 'Astral Rift: The Void Nexus',
    category: 'map',
    slot: 'none',
    equipLoad: 0,
    width: 1,
    height: 1,
    reqLevel: 60,
    reqStr: 0,
    reqDex: 0,
    reqInt: 0,
    icon: 'Compass',
    color: '#a855f7',
    baseStats: {},
  },
};
