// src/constants/mapsData.ts

import { ZoneDefinition } from '../types/maps';

export const ZONES: { [id: string]: ZoneDefinition } = {
  town_havens_watch: {
    id: 'town_havens_watch',
    name: "Haven's Watch Encampment",
    act: 'act1',
    monsterLevel: 1,
    biome: 'town',
    description: 'A fortified cliffside sanctuary overlooking the tempestuous Astris coastline. Survivors gather here to trade, forge gear, and prepare excursions.',
    isTown: true,
    hasWaypoint: true,
    requiredLevel: 1,
    prerequisiteZoneIds: [],
    mapWidth: 1600,
    mapHeight: 1200,
    monsterTypes: [],
    targetKillCount: 0,
    spawnRateMultiplier: 0,
    maxActiveMonsters: 0,
    elitePackChance: 0,
    bossDefinition: {
      id: 'none',
      name: '',
      title: '',
      level: 1,
      baseLife: 0,
      baseArmor: 0,
      attacks: [],
      phases: 1,
      visualScale: 1,
      tint: '#ffffff',
    },
    backgroundColor: '#0c0f17',
    gridColor: '#172033',
    ambientLight: '#38bdf8',
    obstacleType: 'rocks',
    obstacleCount: 8,
    baseItemQuantity: 0,
    baseItemRarity: 0,
    dropTierBonus: 0,
  },
  ashen_coast: {
    id: 'ashen_coast',
    name: 'The Ashen Coast',
    act: 'act1',
    monsterLevel: 1,
    biome: 'coast',
    description: 'A wave-battered shoreline covered in black volcanic sand and rising drowned mariners.',
    isTown: false,
    hasWaypoint: true,
    requiredLevel: 1,
    prerequisiteZoneIds: [],
    mapWidth: 2600,
    mapHeight: 2200,
    monsterTypes: ['drowned_mariner', 'armored_crab', 'ashen_scavenger'],
    targetKillCount: 60,
    spawnRateMultiplier: 1.0,
    maxActiveMonsters: 75,
    elitePackChance: 0.12,
    bossDefinition: {
      id: 'boss_ghal_mor',
      name: 'Ghal-Mor the Drowned Brute',
      title: 'Leviathan of the Shallows',
      level: 2,
      baseLife: 850,
      baseArmor: 80,
      attacks: ['heavy_smash', 'corrosive_bile', 'berserk_rush'],
      phases: 2,
      visualScale: 2.2,
      tint: '#38bdf8',
    },
    backgroundColor: '#07131b',
    gridColor: '#0e2b3d',
    ambientLight: '#38bdf8',
    obstacleType: 'rocks',
    obstacleCount: 16,
    baseItemQuantity: 1.0,
    baseItemRarity: 1.0,
    dropTierBonus: 1,
  },
  murkwood_mire: {
    id: 'murkwood_mire',
    name: 'The Murkwood Mire',
    act: 'act1',
    monsterLevel: 4,
    biome: 'swamp',
    description: 'A noxious, overgrown bog choked with toxic spore spitters and submerged predators.',
    isTown: false,
    hasWaypoint: true,
    requiredLevel: 3,
    prerequisiteZoneIds: ['ashen_coast'],
    mapWidth: 2800,
    mapHeight: 2400,
    monsterTypes: ['bog_stalker', 'spore_spitter', 'mire_leech', 'viper_crawler'],
    targetKillCount: 90,
    spawnRateMultiplier: 1.2,
    maxActiveMonsters: 90,
    elitePackChance: 0.18,
    bossDefinition: {
      id: 'boss_brood_matriarch',
      name: 'Matriarch of the Brood',
      title: 'Queen of the Venomous Mire',
      level: 5,
      baseLife: 1950,
      baseArmor: 140,
      attacks: ['poison_spores', 'swamp_geyser', 'leech_swarm'],
      phases: 2,
      visualScale: 2.4,
      tint: '#22c55e',
    },
    backgroundColor: '#0d180f',
    gridColor: '#17301c',
    ambientLight: '#4ade80',
    obstacleType: 'trees',
    obstacleCount: 22,
    baseItemQuantity: 1.2,
    baseItemRarity: 1.2,
    dropTierBonus: 1,
  },
  aetherial_chasm: {
    id: 'aetherial_chasm',
    name: 'Aetherial Chasm',
    act: 'act1',
    monsterLevel: 8,
    biome: 'cavern',
    description: 'Subterranean tunnels glowing with resonant crystals and crawling with ancient stone golems.',
    isTown: false,
    hasWaypoint: true,
    requiredLevel: 7,
    prerequisiteZoneIds: ['murkwood_mire'],
    mapWidth: 3000,
    mapHeight: 2600,
    monsterTypes: ['crystal_golem', 'cavern_bat', 'subterranean_burrower', 'gem_shard_elemental'],
    targetKillCount: 120,
    spawnRateMultiplier: 1.35,
    maxActiveMonsters: 110,
    elitePackChance: 0.22,
    bossDefinition: {
      id: 'boss_resonant_titan',
      name: 'The Resonant Golem Titan',
      title: 'Heart of the Crystal Deep',
      level: 9,
      baseLife: 3800,
      baseArmor: 280,
      attacks: ['crystal_eruption', 'shatter_slam', 'prismatic_beam'],
      phases: 3,
      visualScale: 2.6,
      tint: '#818cf8',
    },
    backgroundColor: '#090d1f',
    gridColor: '#1a224a',
    ambientLight: '#818cf8',
    obstacleType: 'crystals',
    obstacleCount: 26,
    baseItemQuantity: 1.4,
    baseItemRarity: 1.4,
    dropTierBonus: 2,
  },
  sunken_citadel: {
    id: 'sunken_citadel',
    name: 'The Sunken Citadel',
    act: 'act1',
    monsterLevel: 12,
    biome: 'ruins',
    description: 'Ancient monolithic halls where animated marble sentinels and spectral legions stand eternal guard.',
    isTown: false,
    hasWaypoint: true,
    requiredLevel: 11,
    prerequisiteZoneIds: ['aetherial_chasm'],
    mapWidth: 3200,
    mapHeight: 2800,
    monsterTypes: ['skeleton_phalanx', 'citadel_construct', 'ruin_archon', 'ghostly_legionnaire'],
    targetKillCount: 150,
    spawnRateMultiplier: 1.5,
    maxActiveMonsters: 130,
    elitePackChance: 0.26,
    bossDefinition: {
      id: 'boss_archon_malakor',
      name: 'Archon Malakor',
      title: 'Sovereign of the Sunken Dynasty',
      level: 14,
      baseLife: 6800,
      baseArmor: 420,
      attacks: ['spectral_swords_storm', 'imperial_judgment', 'soul_drain_nova'],
      phases: 3,
      visualScale: 2.8,
      tint: '#f59e0b',
    },
    backgroundColor: '#19140c',
    gridColor: '#362a16',
    ambientLight: '#f59e0b',
    obstacleType: 'ruins_pillars',
    obstacleCount: 30,
    baseItemQuantity: 1.6,
    baseItemRarity: 1.6,
    dropTierBonus: 2,
  },
  magma_caldera: {
    id: 'magma_caldera',
    name: 'The Magma Caldera',
    act: 'act1',
    monsterLevel: 16,
    biome: 'volcano',
    description: 'A subterranean volcanic chamber boiling with molten lava beasts and infernal titans.',
    isTown: false,
    hasWaypoint: true,
    requiredLevel: 15,
    prerequisiteZoneIds: ['sunken_citadel'],
    mapWidth: 3400,
    mapHeight: 3000,
    monsterTypes: ['magma_hound', 'pyro_fiend', 'lava_colossus', 'flame_dancer'],
    targetKillCount: 180,
    spawnRateMultiplier: 1.6,
    maxActiveMonsters: 145,
    elitePackChance: 0.30,
    bossDefinition: {
      id: 'boss_pyrax_unbroken',
      name: 'Pyrax the Unbroken',
      title: 'Titan of the Calamity Hearth',
      level: 18,
      baseLife: 11500,
      baseArmor: 650,
      attacks: ['magma_meteor_shower', 'molten_fissure', 'infernal_cataclysm'],
      phases: 3,
      visualScale: 3.0,
      tint: '#ef4444',
    },
    backgroundColor: '#1c0a0a',
    gridColor: '#421616',
    ambientLight: '#ef4444',
    obstacleType: 'lava_pits',
    obstacleCount: 32,
    baseItemQuantity: 2.0,
    baseItemRarity: 2.0,
    dropTierBonus: 3,
  },

  // --- ASTRAL REALMS (ENDGAME TIERED MAPS) ---
  astral_catacomb_t1: {
    id: 'astral_catacomb_t1',
    name: 'Astral Rift: Catacomb of Echoes',
    act: 'atlas_maps',
    tier: 1,
    monsterLevel: 22,
    biome: 'graveyard',
    description: 'Astral Rift device zone. Infested with elite revenants and cursed relics with boosted item quantity.',
    isTown: false,
    hasWaypoint: false,
    requiredLevel: 20,
    prerequisiteZoneIds: ['magma_caldera'],
    mapWidth: 3500,
    mapHeight: 3200,
    monsterTypes: ['tomb_lord', 'crypt_ghoul', 'dread_phantom', 'cursed_priest'],
    targetKillCount: 200,
    spawnRateMultiplier: 1.8,
    maxActiveMonsters: 160,
    elitePackChance: 0.35,
    bossDefinition: {
      id: 'boss_lord_tombs',
      name: 'Lord of the Tombs',
      title: 'High Necromancer of Echoes',
      level: 24,
      baseLife: 18000,
      baseArmor: 850,
      attacks: ['corpse_explosion_cascade', 'bone_spear_barrage', 'unholy_blight'],
      phases: 3,
      visualScale: 3.2,
      tint: '#a855f7',
    },
    backgroundColor: '#120c18',
    gridColor: '#2b1a38',
    ambientLight: '#c084fc',
    obstacleType: 'ruins_pillars',
    obstacleCount: 35,
    baseItemQuantity: 2.5,
    baseItemRarity: 2.5,
    dropTierBonus: 4,
  },
  astral_spires_t5: {
    id: 'astral_spires_t5',
    name: 'Astral Rift: Solar Spires',
    act: 'atlas_maps',
    tier: 5,
    monsterLevel: 35,
    biome: 'temple',
    description: 'High-tier Astral Rift encounter with high density packs and intense elemental modifiers.',
    isTown: false,
    hasWaypoint: false,
    requiredLevel: 30,
    prerequisiteZoneIds: ['astral_catacomb_t1'],
    mapWidth: 3800,
    mapHeight: 3500,
    monsterTypes: ['solar_zealot', 'flame_archon', 'radiant_templar', 'inferno_golem'],
    targetKillCount: 240,
    spawnRateMultiplier: 2.0,
    maxActiveMonsters: 180,
    elitePackChance: 0.40,
    bossDefinition: {
      id: 'boss_solar_archon',
      name: 'Solar High Archon',
      title: 'Bringer of the Purifying Light',
      level: 38,
      baseLife: 36000,
      baseArmor: 1400,
      attacks: ['solar_flare_ring', 'consecrated_pillars', 'radiant_judgment'],
      phases: 3,
      visualScale: 3.4,
      tint: '#fbbf24',
    },
    backgroundColor: '#1f1609',
    gridColor: '#453215',
    ambientLight: '#fde047',
    obstacleType: 'ruins_pillars',
    obstacleCount: 40,
    baseItemQuantity: 3.2,
    baseItemRarity: 3.0,
    dropTierBonus: 5,
  },
  astral_void_t10: {
    id: 'astral_void_t10',
    name: 'Astral Rift: The Void Nexus',
    act: 'atlas_maps',
    tier: 10,
    monsterLevel: 50,
    biome: 'celestial_arena',
    description: 'Pinnacle Astral encounter in the heart of the void abyss.',
    isTown: false,
    hasWaypoint: false,
    requiredLevel: 45,
    prerequisiteZoneIds: ['astral_spires_t5'],
    mapWidth: 4200,
    mapHeight: 4000,
    monsterTypes: ['void_walker', 'astral_horror', 'cosmic_aberration', 'entropy_spawn'],
    targetKillCount: 300,
    spawnRateMultiplier: 2.2,
    maxActiveMonsters: 200,
    elitePackChance: 0.50,
    bossDefinition: {
      id: 'boss_void_harbinger',
      name: 'The Void Harbinger',
      title: 'Ender of Stars and Worlds',
      level: 55,
      baseLife: 75000,
      baseArmor: 2200,
      attacks: ['black_hole_singularity', 'void_supernova', 'reality_shatter_lasers'],
      phases: 4,
      visualScale: 3.8,
      tint: '#6366f1',
    },
    backgroundColor: '#070714',
    gridColor: '#151538',
    ambientLight: '#818cf8',
    obstacleType: 'crystals',
    obstacleCount: 45,
    baseItemQuantity: 4.5,
    baseItemRarity: 4.5,
    dropTierBonus: 6,
  },
};
