// src/constants/skillGems.ts

import { SkillDefinition, SupportGemEffect } from '../types/skills';

export const ACTIVE_SKILLS: { [id: string]: SkillDefinition } = {
  tectonic_quake: {
    id: 'tectonic_quake',
    name: 'Tectonic Quake',
    icon: 'Hammer',
    description: 'Slams the earth with titanic force, unleashing a cascading shockwave that damages and stuns enemies in a frontal cone. Scales with Strength (Heavy Damage).',
    tags: ['Attack', 'AoE', 'Melee', 'Physical', 'Heavy'],
    scalingType: 'heavy',
    baseCooldown: 0.8,
    baseManaCost: 8,
    baseStaminaCost: 15,
    baseDamageMin: 24,
    baseDamageMax: 42,
    damageScalingPerLevel: 6.5,
    damageType: 'physical',
    castTime: 0.4,
    autoCastInterval: 0.8,
    projectileCount: 1,
    projectileSpeed: 380,
    projectileLifetime: 0.7,
    projectileSpread: 45,
    pierceCount: 99,
    chainCount: 0,
    aoeRadius: 110,
    range: 220,
    projectileColor: '#b45309',
    projectileGlowColor: '#f59e0b',
    projectileRadius: 28,
    behaviorType: 'ground_slam_aoe',
    projectileStyle: 'shockwave_slam',
  },
  whirlwind_steel: {
    id: 'whirlwind_steel',
    name: 'Whirlwind of Steel',
    icon: 'RotateCw',
    description: 'Spin into a deadly cyclone of blades, striking all surrounding enemies continuously while moving freely. Scales with Strength & Dexterity (Hybrid Heavy/Light).',
    tags: ['Attack', 'AoE', 'Melee', 'Physical', 'Heavy', 'Light', 'Movement'],
    scalingType: 'hybrid',
    baseCooldown: 0.15,
    baseManaCost: 3,
    baseStaminaCost: 5,
    baseDamageMin: 14,
    baseDamageMax: 26,
    damageScalingPerLevel: 3.8,
    damageType: 'physical',
    castTime: 0.1,
    autoCastInterval: 0.18,
    projectileCount: 1,
    projectileSpeed: 0,
    projectileLifetime: 0.2,
    projectileSpread: 0,
    pierceCount: 99,
    chainCount: 0,
    aoeRadius: 95,
    range: 100,
    projectileColor: '#e2e8f0',
    projectileGlowColor: '#cbd5e1',
    projectileRadius: 95,
    behaviorType: 'orbiting_blades',
    projectileStyle: 'steel_cyclone',
  },
  volley_barrage: {
    id: 'volley_barrage',
    name: 'Volley Barrage',
    icon: 'Target',
    description: 'Fires a wide volley of high-velocity piercing arrows that tear through enemy packs. Scales with Dexterity (Light Damage).',
    tags: ['Attack', 'Projectile', 'Bow', 'Physical', 'Light'],
    scalingType: 'light',
    baseCooldown: 0.45,
    baseManaCost: 6,
    baseStaminaCost: 10,
    baseDamageMin: 16,
    baseDamageMax: 30,
    damageScalingPerLevel: 5,
    damageType: 'physical',
    castTime: 0.25,
    autoCastInterval: 0.45,
    projectileCount: 5,
    projectileSpeed: 580,
    projectileLifetime: 1.4,
    projectileSpread: 50,
    pierceCount: 2,
    chainCount: 0,
    aoeRadius: 25,
    range: 550,
    projectileColor: '#22c55e',
    projectileGlowColor: '#86efac',
    projectileRadius: 6,
    behaviorType: 'spread_projectile',
    projectileStyle: 'arrow_bolt',
  },
  sporefall_barrage: {
    id: 'sporefall_barrage',
    name: 'Sporefall Barrage',
    icon: 'Droplets',
    description: 'Launches a cluster of toxic spore pods that burst in corrosive poison clouds. Scales with Dexterity & Wisdom (Light/Magical).',
    tags: ['Attack', 'AoE', 'Bow', 'Chaos', 'Projectile', 'Light', 'Magical'],
    scalingType: 'hybrid',
    baseCooldown: 0.7,
    baseManaCost: 11,
    baseStaminaCost: 12,
    baseDamageMin: 16,
    baseDamageMax: 32,
    damageScalingPerLevel: 5.5,
    damageType: 'chaos',
    castTime: 0.3,
    autoCastInterval: 0.7,
    projectileCount: 6,
    projectileSpeed: 450,
    projectileLifetime: 1.5,
    projectileSpread: 60,
    pierceCount: 99,
    chainCount: 0,
    aoeRadius: 90,
    range: 460,
    projectileColor: '#84cc16',
    projectileGlowColor: '#a3e635',
    projectileRadius: 10,
    behaviorType: 'toxic_rain',
    projectileStyle: 'spore_pod',
  },
  firestorm_orb: {
    id: 'firestorm_orb',
    name: 'Firestorm Orb',
    icon: 'Flame',
    description: 'Hurls an incandescent orb of plasma that detonates in a fiery explosion upon impact. Scales with Wisdom (Magical Damage).',
    tags: ['Spell', 'Projectile', 'AoE', 'Fire', 'Magical'],
    scalingType: 'magical',
    baseCooldown: 0.5,
    baseManaCost: 10,
    baseDamageMin: 26,
    baseDamageMax: 46,
    damageScalingPerLevel: 7.5,
    damageType: 'fire',
    castTime: 0.3,
    autoCastInterval: 0.5,
    projectileCount: 1,
    projectileSpeed: 480,
    projectileLifetime: 1.6,
    projectileSpread: 0,
    pierceCount: 0,
    chainCount: 0,
    aoeRadius: 90,
    range: 520,
    projectileColor: '#ef4444',
    projectileGlowColor: '#f97316',
    projectileRadius: 14,
    behaviorType: 'straight_projectile',
    projectileStyle: 'fire_orb',
  },
  volt_jolt: {
    id: 'volt_jolt',
    name: 'Volt Jolt',
    icon: 'Zap',
    description: 'Releases erratic discharges of bouncing electric sparks that shock enemies. Scales with Wisdom (Magical Damage).',
    tags: ['Spell', 'Projectile', 'Lightning', 'Magical'],
    scalingType: 'magical',
    baseCooldown: 0.4,
    baseManaCost: 9,
    baseDamageMin: 8,
    baseDamageMax: 50,
    damageScalingPerLevel: 6,
    damageType: 'lightning',
    castTime: 0.25,
    autoCastInterval: 0.4,
    projectileCount: 4,
    projectileSpeed: 420,
    projectileLifetime: 2.2,
    projectileSpread: 120,
    pierceCount: 3,
    chainCount: 1,
    aoeRadius: 20,
    range: 600,
    projectileColor: '#38bdf8',
    projectileGlowColor: '#67e8f9',
    projectileRadius: 8,
    behaviorType: 'spark_bouncing',
    projectileStyle: 'spark_bolt',
  },
  celestial_retribution: {
    id: 'celestial_retribution',
    name: 'Celestial Retribution',
    icon: 'Sun',
    description: 'Calls down a column of radiant fire from above, crushing enemies. Scales with Strength & Wisdom (Heavy Magical Damage).',
    tags: ['Spell', 'AoE', 'Lightning', 'Fire', 'Heavy', 'Magical'],
    scalingType: 'hybrid',
    baseCooldown: 1.0,
    baseManaCost: 14,
    baseDamageMin: 36,
    baseDamageMax: 68,
    damageScalingPerLevel: 9.5,
    damageType: 'fire',
    castTime: 0.35,
    autoCastInterval: 1.0,
    projectileCount: 1,
    projectileSpeed: 0,
    projectileLifetime: 0.8,
    projectileSpread: 0,
    pierceCount: 99,
    chainCount: 0,
    aoeRadius: 130,
    range: 350,
    projectileColor: '#fbbf24',
    projectileGlowColor: '#fef08a',
    projectileRadius: 120,
    behaviorType: 'holy_smite',
    projectileStyle: 'holy_smite',
  },
  frostbite_wave: {
    id: 'frostbite_wave',
    name: 'Frostbite Wave',
    icon: 'Snowflake',
    description: 'Unleashes a wide freezing wave that chills and shatters enemy ranks. Scales with Wisdom (Magical Damage).',
    tags: ['Spell', 'Projectile', 'Cold', 'Magical'],
    scalingType: 'magical',
    baseCooldown: 0.45,
    baseManaCost: 8,
    baseDamageMin: 20,
    baseDamageMax: 36,
    damageScalingPerLevel: 6,
    damageType: 'cold',
    castTime: 0.25,
    autoCastInterval: 0.45,
    projectileCount: 1,
    projectileSpeed: 520,
    projectileLifetime: 1.0,
    projectileSpread: 0,
    pierceCount: 99,
    chainCount: 0,
    aoeRadius: 40,
    range: 480,
    projectileColor: '#60a5fa',
    projectileGlowColor: '#93c5fd',
    projectileRadius: 18,
    behaviorType: 'straight_projectile',
    projectileStyle: 'frost_shard',
  },
  orbiting_glaives: {
    id: 'orbiting_glaives',
    name: 'Orbiting Glaives',
    icon: 'Disc',
    description: 'Conjures a vortex of spectral razor glaives that orbit around the character. Scales with Dexterity & Wisdom (Light Magical Damage).',
    tags: ['Spell', 'AoE', 'Physical', 'Light', 'Magical'],
    scalingType: 'hybrid',
    baseCooldown: 0.25,
    baseManaCost: 5,
    baseDamageMin: 12,
    baseDamageMax: 20,
    damageScalingPerLevel: 3.5,
    damageType: 'physical',
    castTime: 0.15,
    autoCastInterval: 0.25,
    projectileCount: 1,
    projectileSpeed: 0,
    projectileLifetime: 4.0,
    projectileSpread: 0,
    pierceCount: 99,
    chainCount: 0,
    aoeRadius: 110,
    range: 120,
    projectileColor: '#cbd5e1',
    projectileGlowColor: '#94a3b8',
    projectileRadius: 110,
    behaviorType: 'blade_vortex',
    projectileStyle: 'glaive_ring',
  },
  thunderchain: {
    id: 'thunderchain',
    name: 'Thunderchain',
    icon: 'Zap',
    description: 'Strikes a foe with high-voltage lightning, instantly branching to fry multiple nearby enemies. Scales with Wisdom (Magical Damage).',
    tags: ['Spell', 'Chaining', 'Lightning', 'Magical'],
    scalingType: 'magical',
    baseCooldown: 0.6,
    baseManaCost: 12,
    baseDamageMin: 18,
    baseDamageMax: 60,
    damageScalingPerLevel: 8.5,
    damageType: 'lightning',
    castTime: 0.3,
    autoCastInterval: 0.6,
    projectileCount: 1,
    projectileSpeed: 900,
    projectileLifetime: 0.5,
    projectileSpread: 0,
    pierceCount: 0,
    chainCount: 5,
    aoeRadius: 30,
    range: 450,
    projectileColor: '#38bdf8',
    projectileGlowColor: '#bae6fd',
    projectileRadius: 10,
    behaviorType: 'chain_lightning',
    projectileStyle: 'lightning_arc',
  },
  radiant_pyre: {
    id: 'radiant_pyre',
    name: 'Radiant Pyre',
    icon: 'Flame',
    description: 'Ignites an aura of solar flame around you, burning nearby enemies for fire damage scaling with your max life. Scales with Vigor & Wisdom.',
    tags: ['Spell', 'AoE', 'Fire', 'Aura', 'Magical'],
    scalingType: 'magical',
    baseCooldown: 0.2,
    baseManaCost: 0,
    baseDamageMin: 16,
    baseDamageMax: 28,
    damageScalingPerLevel: 4.5,
    damageType: 'fire',
    castTime: 0,
    autoCastInterval: 0.25,
    projectileCount: 1,
    projectileSpeed: 0,
    projectileLifetime: 999,
    projectileSpread: 0,
    pierceCount: 99,
    chainCount: 0,
    aoeRadius: 140,
    range: 140,
    projectileColor: '#ea580c',
    projectileGlowColor: '#fb923c',
    projectileRadius: 140,
    behaviorType: 'righteous_fire_aura',
    projectileStyle: 'solar_aura',
  },
  blazing_step: {
    id: 'blazing_step',
    name: 'Blazing Step',
    icon: 'FastForward',
    description: 'Instantly warp forward in a burst of speed, leaving a trail of searing fire. Scales with Dexterity & Wisdom (Light/Magical).',
    tags: ['Spell', 'Movement', 'Fire', 'Light', 'Magical'],
    scalingType: 'hybrid',
    baseCooldown: 2.0,
    baseManaCost: 15,
    baseDamageMin: 22,
    baseDamageMax: 38,
    damageScalingPerLevel: 5.5,
    damageType: 'fire',
    castTime: 0.1,
    autoCastInterval: 2.0,
    projectileCount: 1,
    projectileSpeed: 0,
    projectileLifetime: 0.3,
    projectileSpread: 0,
    pierceCount: 99,
    chainCount: 0,
    aoeRadius: 70,
    range: 220,
    projectileColor: '#f97316',
    projectileGlowColor: '#fdba74',
    projectileRadius: 50,
    behaviorType: 'dash_movement',
    projectileStyle: 'blaze_trail',
  },
};

export const SUPPORT_GEMS: { [id: string]: SupportGemEffect } = {
  multiplex_barrage: {
    id: 'multiplex_barrage',
    name: 'Multiplex Barrage',
    description: 'Supported skills fire +4 additional projectiles in an expanded arc.',
    tags: ['Projectile'],
    manaMultiplier: 1.4,
    modifiers: {
      extraProjectiles: 4,
      moreDamage: -0.15,
  },
  },
  echoing_cadence: {
    id: 'echoing_cadence',
    name: 'Echoing Cadence',
    description: 'Supported spells repeat 1 additional time with 40% increased Cast Speed.',
    tags: ['Spell'],
    manaMultiplier: 1.5,
    modifiers: {
      castSpeedMultiplier: 0.40,
      moreDamage: 0.10,
    },
  },
  chain_resonance: {
    id: 'chain_resonance',
    name: 'Chain Resonance',
    description: 'Supported projectiles chain +2 times to nearby enemies.',
    tags: ['Projectile', 'Chaining'],
    manaMultiplier: 1.35,
    modifiers: {
      chainCount: 2,
      moreDamage: -0.08,
    },
  },
  pierce_penetrator: {
    id: 'pierce_penetrator',
    name: 'Pierce Penetrator',
    description: 'Supported projectiles pierce +3 additional targets with bonus projectile damage.',
    tags: ['Projectile'],
    manaMultiplier: 1.2,
    modifiers: {
      pierceCount: 3,
      moreDamage: 0.15,
    },
  },
  devastating_impact: {
    id: 'devastating_impact',
    name: 'Devastating Impact',
    description: 'Grants +75% Critical Strike Multiplier and +15% Critical Strike Chance.',
    tags: ['Attack', 'Spell'],
    manaMultiplier: 1.25,
    modifiers: {
      critMultiplierBonus: 75,
      critChanceBonus: 15,
    },
  },
  focal_intensity: {
    id: 'focal_intensity',
    name: 'Focal Intensity',
    description: 'Decreases Area of Effect by 20%, but grants +45% MORE Area Damage.',
    tags: ['AoE'],
    manaMultiplier: 1.3,
    modifiers: {
      areaMultiplier: -0.20,
      moreDamage: 0.45,
    },
  },
  pyro_infusion: {
    id: 'pyro_infusion',
    name: 'Pyro Infusion',
    description: 'Adds Fire Damage to hits and grants +20% Chance to Ignite.',
    tags: ['Attack', 'Spell', 'Fire'],
    manaMultiplier: 1.25,
    modifiers: {
      moreDamage: 0.25,
      chanceToIgnite: 20,
    },
  },
  kinetic_celerity: {
    id: 'kinetic_celerity',
    name: 'Kinetic Celerity',
    description: 'Supported attacks have 35% increased Attack Speed.',
    tags: ['Attack'],
    manaMultiplier: 1.15,
    modifiers: {
      castSpeedMultiplier: 0.35,
    },
  },
  siphon_essence: {
    id: 'siphon_essence',
    name: 'Siphon Essence',
    description: 'Leeches 2.5% of damage dealt back as Life.',
    tags: ['Attack', 'Spell'],
    manaMultiplier: 1.15,
    modifiers: {
      lifeLeechPercent: 2.5,
    },
  },
};
