// src/constants/uniques.ts

import { Item } from '../types/items';

export const UNIQUE_ITEMS: { [id: string]: Partial<Item> } = {
  crown_of_resonances: {
    id: 'unique_crown_of_resonances',
    baseId: 'hunter_hood',
    name: 'Crown of Resonances',
    baseName: 'Hunter Hood',
    rarity: 'unique',
    category: 'armour_helmet',
    slot: 'helmet',
    reqLevel: 1,
    reqStr: 0,
    reqDex: 10,
    reqInt: 0,
    quality: 20,
    isIdentified: true,
    evasion: 55,
    uniqueModifiers: [
      '+35% to all Elemental Resistances',
      '+40 to Evasion Rating',
      '+10% increased Item Rarity',
    ],
    flavorText: 'A radiant circlet vibrating with harmonic protective resonance.',
    icon: 'Crown',
    iconColor: '#eab308',
  },
  fleetstride_wraps: {
    id: 'unique_fleetstride_wraps',
    baseId: 'iron_greaves',
    name: 'Fleetstride Wraps',
    baseName: 'Iron Greaves',
    rarity: 'unique',
    category: 'armour_boots',
    slot: 'boots',
    reqLevel: 1,
    reqStr: 8,
    reqDex: 0,
    reqInt: 0,
    quality: 20,
    isIdentified: true,
    armor: 30,
    uniqueModifiers: [
      '+25% increased Movement Speed',
      'Cannot be Frozen or Chilled',
      '+15 to Maximum Energy Shield',
      '+5 Mana Regeneration per second',
    ],
    flavorText: 'No frost may bind the stride of the celestial wanderer.',
    icon: 'Footprints',
    iconColor: '#38bdf8',
  },
  the_primal_canvas: {
    id: 'unique_primal_canvas',
    baseId: 'silk_robe',
    name: 'The Primal Canvas',
    baseName: 'Silk Robe',
    rarity: 'unique',
    category: 'armour_body',
    slot: 'bodyArmor',
    reqLevel: 1,
    reqStr: 0,
    reqDex: 0,
    reqInt: 0,
    quality: 20,
    isIdentified: true,
    energyShield: 0,
    uniqueModifiers: [
      'Has 6 Fully Linked Sockets (Grants +35% More Global Damage)',
      '+20 to All Attributes',
      '+1 to Level of all Equipped Skill Gems',
    ],
    flavorText: 'An immaculate weave upon which legend is scripted without restraint.',
    icon: 'Shirt',
    iconColor: '#ffffff',
  },
  igneous_bastion: {
    id: 'unique_igneous_bastion',
    baseId: 'astral_plate',
    name: 'Igneous Bastion',
    baseName: 'Astral Plate',
    rarity: 'unique',
    category: 'armour_body',
    slot: 'bodyArmor',
    reqLevel: 25,
    reqStr: 60,
    reqDex: 0,
    reqInt: 0,
    quality: 20,
    isIdentified: true,
    armor: 450,
    uniqueModifiers: [
      '+500 to Maximum Life',
      '+40% increased Fire Damage',
      '+15% to Fire Resistance',
      '+10 Life Regeneration per second',
    ],
    flavorText: 'Forged within the blazing heart of the primordial caldera.',
    icon: 'Shirt',
    iconColor: '#dc2626',
  },
  sovereigns_trophy: {
    id: 'unique_sovereigns_trophy',
    baseId: 'leather_belt',
    name: "Sovereign's Trophy",
    baseName: 'Leather Belt',
    rarity: 'unique',
    category: 'accessory_belt',
    slot: 'belt',
    reqLevel: 30,
    reqStr: 0,
    reqDex: 0,
    reqInt: 0,
    quality: 20,
    isIdentified: true,
    uniqueModifiers: [
      '+55 to Maximum Life',
      '+40 to Strength and Dexterity',
      'When you Kill a Rare Monster, you steal its traits for 20 seconds!',
      '+30% increased Damage with Hits against Rare & Boss Monsters',
    ],
    flavorText: 'A band adorned with emblems of vanquished leviathans.',
    icon: 'Link',
    iconColor: '#e11d48',
  },
  zephyrs_splitter: {
    id: 'unique_zephyrs_splitter',
    baseId: 'composite_bow',
    name: "Zephyr's Splitter",
    baseName: 'Composite Bow',
    rarity: 'unique',
    category: 'weapon_bow',
    slot: 'mainHand',
    reqLevel: 25,
    reqStr: 0,
    reqDex: 45,
    reqInt: 0,
    quality: 20,
    isIdentified: true,
    physicalDamageMin: 25,
    physicalDamageMax: 60,
    attackSpeed: 1.55,
    critChance: 8.5,
    uniqueModifiers: [
      'Adds 15 to 30 Cold Damage to Attacks',
      'Adds 1 to 50 Lightning Damage to Attacks',
      '+15% increased Item Quantity from Shattered Enemies',
      '+30% increased Item Rarity from Shocked Enemies',
      '+1 Additional Projectile fired',
    ],
    flavorText: 'A string pulled by the howling gales of Astris.',
    icon: 'Target',
    iconColor: '#06b6d4',
  },
  avarice_talisman: {
    id: 'unique_avarice_talisman',
    baseId: 'amber_amulet',
    name: 'Avarice Talisman',
    baseName: 'Amber Amulet',
    rarity: 'unique',
    category: 'accessory_amulet',
    slot: 'amulet',
    reqLevel: 20,
    reqStr: 0,
    reqDex: 0,
    reqInt: 0,
    quality: 20,
    isIdentified: true,
    uniqueModifiers: [
      '+35% increased Item Quantity',
      '+75% increased Item Rarity',
      '+50px Item Pickup Radius',
      '+15% increased Movement Speed',
    ],
    flavorText: 'Fortune smiles upon those who dare delve into the abyss.',
    icon: 'Gem',
    iconColor: '#f59e0b',
  },
};
